name: Link Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true  # Automatically caches gems based on Gemfile.lock and installs dependencies
      
      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: Install HTMLProofer
        run: gem install html-proofer
      
      - name: Run HTMLProofer
        run: |
          htmlproofer ./_site \
            --disable-external \
            --allow-hash-href \
            --ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/,/^http:\/\/pi.hole/"
